### ISSUE TITLE
Decouple Discovery from services

### ISSUE THREAD

**Issue by ronenhamias** [ronenhamias/scalecube-services#161]
**Motivation**

Scalecube services are using scalecube cluster as its main discovery provider.
decoupling  the discovery from scalecube services will allow the user to choose or create its own discovery provider using a plug and play (ServiceLoader).

**Comment by bsideup** [comment]
I would also like to use Scalecube's service abstraction (ServiceMessage, annotation parsing, calls) without using the discovery at all. More like a wrapper for RSocket's generic request/response API


My motivation:
I want to replace the use of gRPC services with RSocket, and I was looking for "services" abstraction for it. Scalecube looks like a solid option, so I want to reuse its definitions, so that I don't have to create my own `ServiceMessage`-like classes and annotation parsing of service definitions

**Comment by ronenhamias** [comment]
@bsideup i think it will be good idea.
in such case one will have to provide an endpoint to its services address
when you aim to use grpc you mean by creating a grpc transport?

**Comment by bsideup** [comment]
@ronenhamias well, I'm not aiming to use gRPC but rather **replace** it with RSocket + Scalecube services ;)

**Comment by ronenhamias** [comment]
@bsideup in such case how the usage will look like this?

```
Call.builder().address(address).create().api(MyService.class);
```

**Comment by bsideup** [comment]
@ronenhamias precisely :) 

I could do that without Scalecube at all, just by defining my own `ServiceCall`-like message but then I will just redo what you already did :)
So, I want to re-use Scalecube's definitions & service interface parsing because I think it suits my need quite well :)

But I have my own discovery mechanism, very specific, so I cannot rely on Scalecube's discovery, at least not yet

**Comment by ronenhamias** [comment]
so its two things we want to do
one thing is we want to decouple scalecube services from discovery 
secound thing we want to allow to create call by address (without discovery)

becouse today call inherit discovery from microservices

**Comment by bsideup** [comment]
ah, ok. Then yes, the result I want to get:
Very thin wrapper around RSocket to allow publishing & subscribing by service & method names :)

**Comment by ronenhamias** [comment]
So actually the main effort is around decoupling the discovery from Microservices.
microservices is the one provisioning and registering service endpoints and make them avaliable

the Call side is straight forward its very simple to do.

we can sketch this solution together if you like.


What i have in mind is:
1. move discovery to separated maven module with relevant api.
2. make microservices discover the module in ServiceLoader
3. in case not provided Microservices will work without discovery and will just provision the endpoints.
4. adjust service call to have address and builder without microservices.

Benefits:

in such case we can have more then one discovery providers and scalecube discovery is just one impl
in future you might want to implement your own discovery so the model will remain the same. 
we might allow several discovery providers work side by side contributing endpoints to service registry.

switching between discovery will be seamless as working without discovery.

started a branch here:

https://github.com/scalecube/scalecube-services/tree/decouple_scalecube_discovery

**Comment by bsideup** [comment]
@ronenhamias I would be happy to help :)

**Comment by ronenhamias** [comment]
Better to separate the question regards RPC from actual decoupling the discovery from services
the RPC mode should be discussed in separated issue
